projconfs:
    path:     /
    defaults: { _controller: "CasanetBundle:Projconf:index" }

projconf_show:
    path:     /{id}/show
    defaults: { _controller: "CasanetBundle:Projconf:show" }

projconf_new:
    path:     /new
    defaults: { _controller: "CasanetBundle:Projconf:new" }

projconf_create:
    path:     /create
    defaults: { _controller: "CasanetBundle:Projconf:create" }
    methods:  POST

projconf_edit:
    path:     /{id}/edit
    defaults: { _controller: "CasanetBundle:Projconf:edit" }

projconf_update:
    path:     /{id}/update
    defaults: { _controller: "CasanetBundle:Projconf:update" }
    methods:  [POST, PUT]

projconf_delete:
    path:     /{id}/delete
    defaults: { _controller: "CasanetBundle:Projconf:delete" }

