<?php

namespace UIR\CasanetBundle\Entity;

/**
 * ProjconfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjconfRepository extends \Doctrine\ORM\EntityRepository
{
}
